stream-to-kafka-service:
  active-model: infinite
  fixedCount: 10
  min-stream-interval-ms: 1000
  max-stream-interval-ms: 5000
  welcome-message: Hello microservices!
  helper:
    stream-content-sources:
      - JAVA
      - Microservices
      - Kafka
      - Elasticsearch
    min-text-length: 5
    max-text-length: 10
