stream-to-kafka-service:
  stream-content-sources:
    - JAVA
    - Microservices
    - Kafka
    - Elasticsearch
  min-stream-interval-ms: 1000
  max-stream-interval-ms: 5000
  welcome-message: Hello microservices!
  enable-v1-streamer: false