stream-to-kafka-service:
  active-model: fixed
  fixedCount: 3
  min-stream-interval-ms: 1000
  max-stream-interval-ms: 5000
  welcome-message: Hello microservices!
  helper:
    stream-content-sources:
      - JAVA
      - Microservices
      - Kafka
      - Elasticsearch
    min-text-length: 5
    max-text-length: 10

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000